apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template: 
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:17
          resources: 
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 5432
          env: 
            - name: POSTGRES_PASSWORD
              value: pg@123
            - name: POSTGRES_USER
              value: meudinheiro
            - name: POSTGRES_DB
              value: meudinheiro_DB
---
apiVersion: v1
kind: Service
metadata: 
  name: postgre
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgre
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudinheiro
spec:
  replicas: 4
  selector:
    matchLabels:
      app: meudinheiro
  template: 
    metadata:
      labels:
        app: meudinheiro
    spec:
      containers:
        - name: meudinheiro
          image: sirzechhs/meudinheiro:v3
          resources: 
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata: 
  name: meudinheiro
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: meudinheiro