name: CI-CD
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Obter o Codigo do repositorio
        uses: actions/checkout@v4.2.2
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e push docker image
        uses: docker/build-push-action@v6
        with:
          context: "./MeuDinheiro"
          push: true
          file: "./MeuDinheiro/Dockerfile"
          tags: sirzechhs/meudinheiro:v3
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "configurar o kubeconfig"
      - run: echo "executar apply"
