name: CI-CD
on:
  merge_group:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Obter o Codigo do repositorio
        uses: actions/checkout@v4.2.2
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build e push docker image
        uses: docker/build-push-action@v6
        with:
          context: "./MeuDinheiro"
          push: true
          file: "./MeuDinheiro/Dockerfile"
          tags: |
            sirzechhs/meudinheiro:v${{ github.run_number }}
            sirzechhs/meudinheiro
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Obter o Codigo do repositorio
        uses: actions/checkout@v4.2.2
      - uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.K8S_KUBECONFIG }}
      - uses: Azure/k8s-deploy@v5
        with:
          manifests: k8s/deployment.yaml
          images: sirzechhs/meudinheiro:v${{ github.run_number }}
